const menu = {
  restaurante: {
    nome: "Costelão do Paraíba",
    tipo: "Churrascaria",
    taxa_servico_percentual: 10,
  },
  cervejas_600ml: [
    { nome: "Brahma Duplo Malte", preco: 12.0 },
    { nome: "Stella Artois", preco: 16.0 },
    { nome: "Spaten", preco: 14.0 },
    { nome: "Original", preco: 14.0 },
    { nome: "Budweiser", preco: 12.0 },
    { nome: "Skol", preco: 12.0 },
    { nome: "Bohemia", preco: 12.0 },
    { nome: "Heineken", preco: 18.0 },
    { nome: "Amstel", preco: 12.0 },
    { nome: "Petra", preco: 10.0 },
    { nome: "Devassa", preco: 10.0 },
    { nome: "Itaipava", preco: 9.0 },
    { nome: "Brahma Chopp", preco: 10.0 },
  ],
  bebidas_nao_alcoolicas: {
    lata: [
      { nome: "Guaraná Antarctica Lata", preco: 6.0 },
      { nome: "Guaraná Antarctica Zero Lata", preco: 6.0 },
      { nome: "Pepsi Lata", preco: 6.0 },
      { nome: "Pepsi Black Lata", preco: 6.0 },
      { nome: "Coca-Cola Lata", preco: 6.0 },
    ],
    um_litro: [
      { nome: "Guaraná Antarctica 1L", preco: 10.0 },
      { nome: "Guaraná Antarctica Zero 1L", preco: 10.0 },
      { nome: "Pepsi 1L", preco: 10.0 },
      { nome: "Pepsi Black 1L", preco: 10.0 },
      { nome: "Coca-Cola 1L", preco: 10.0 },
      { nome: "Coca-Cola Zero 1L", preco: 10.0 },
      { nome: "São Geraldo 1L", preco: 12.0 },
    ],
    um_meio_litro: [
      { nome: "Guaraná Antarctica 1.5L", preco: 14.0 },
      { nome: "Coca-Cola 1.5L", preco: 14.0 },
      { nome: "Fanta 1.5L", preco: 14.0 },
    ],
    dois_litros: [
      { nome: "Guaraná Antarctica 2L", preco: 16.0 },
      { nome: "Coca-Cola 2L", preco: 18.0 },
      { nome: "São Geraldo 2L", preco: 18.0 },
    ],
    outros: [
      { nome: "Red Bull", preco: 18.0 },
      { nome: "Água Mineral", preco: 3.5 },
      { nome: "Água Mineral com Gás", preco: 4.5 },
    ],
  },
  carnes_100g: [
    { nome: "Costelinha Suína", preco: 13.99 },
    { nome: "Costela", preco: 13.99 },
    { nome: "Cupim", preco: 13.99 },
    { nome: "Fraldão", preco: 13.99 },
    { nome: "Lombo Suíno", preco: 13.99 },
    { nome: "Maminha", preco: 13.99 },
    { nome: "Carne do Sol", preco: 13.99 },
    { nome: "Picanha Bovina", preco: 13.99 },
    { nome: "Linguiça", preco: 13.99 },
    { nome: "Contra Filé", preco: 13.99 },
    { nome: "Picanha Suína", preco: 13.99 },
    { nome: "Carneiro", preco: 13.99 },
    { nome: "Panceta Suína", preco: 13.99 },
    { nome: "Linguiça Apimentada", preco: 8.8 },
    { nome: "Coxa e Sobrecoxa", preco: 8.8 },
  ],
  porcoes: [
    { nome: "Batata", preco: 20.0 },
    { nome: "Macaxeira", preco: 20.0 },
    { nome: "Baião Simples", preco: 22.0 },
    { nome: "Baião Cremoso", preco: 25.0 },
    { nome: "Arroz Branco", preco: 20.0 },
    { nome: "Macarrão", preco: 2.0 },
    { nome: "Purê de Batata", preco: 12.0 },
    { nome: "Salada Especial", preco: 20.0 },
    { nome: "Feijoada", preco: 25.0 },
    { nome: "Feijão Tropeiro", preco: 28.0 },
    // { nome: "Galinha Caipira", preco: 130.0 },
    { nome: "Prato Feito", preco: 22.0 },
  ],
  combos: [
    {
      nome: "Combo 1kg",
      descricao:
        "1kg Carne + Baião ou Arroz (Branco ou Carreteiro) + Batata + Macarrão + farofa + vinagrete",
      preco: 180.0,
      serve: "5 - 6",
    },
    {
      nome: "Combo 700g",
      descricao:
        "700g carne + Baião ou Arroz (Branco ou Carreteiro) + Batata + Macarrão + farofa + vinagrete",
      preco: 160.0,
      serve: "4 - 5",
    },
    {
      nome: "Combo 500g",
      descricao:
        "500g carne + Baião ou Arroz (Branco ou Carreteiro) + Batata + Macarrão + farofa + vinagrete",
      preco: 126.0,
      serve: "3 - 4",
    },
    {
      nome: "Combo 01",
      descricao: "300g Costela + Baião ou Arroz + Farofa + Vinagrete",
      preco: 59.99,
      serve: "2",
    },
    {
      nome: "Combo 02",
      descricao: "300g Cupim + Baião ou Arroz + Farofa + Vinagrete",
      preco: 59.99,
      serve: "2",
    },
    {
      nome: "Combo 03",
      descricao: "300g Maminha + Baião ou Arroz + Farofa + Vinagrete",
      preco: 57.99,
      serve: "2",
    },
    {
      nome: "Combo 04",
      descricao:
        "300g Lombinho Suíno ou Costelinha Suina + Baião ou Arroz + Farofa + Vinagrete",
      preco: 59.99,
      serve: "2",
    },
    {
      nome: "Combo 05",
      descricao: "500g Misto + Baião ou Arroz + Farofa + Vinagrete",
      preco: 86.99,
      serve: "3 - 4",
    },
    {
      nome: "Combo 06",
      descricao: "300g Carne de Sol + Baião ou Arroz + Farofa + Vinagrete",
      preco: 75.99,
      serve: "2",
    },
    {
      nome: "Combo 07",
      descricao: "300g Contra Filé + Baião ou Arroz + Farofa + Vinagrete",
      preco: 75.99,
      serve: "2",
    },
    {
      nome: "Combo 08",
      descricao: "500g Fraudão + Baião ou Arroz + Farofa + Vinagrete",
      preco: 75.99,
      serve: "3 - 4",
    },
    {
      nome: "Combo 09",
      descricao: "300g Picanha Suína + Baião ou Arroz + Farofa + Vinagrete",
      preco: 73.99,
      serve: "2",
    },
  ],
  sucos: [
    { nome: "Suco de Fruta (Copo)", preco: 9.0 },
    { nome: "Suco de Fruta (Jarra)", preco: 20.0 },
    { nome: "Suco da Polpa (Copo)", preco: 9.0 },
    { nome: "Suco da Polpa (Jarra)", preco: 20.0 },
  ],
};

export default menu;
